### ISSUE TITLE
按教程搭建了 hostwinds 的 SSR 服务器，但是只用了一个下午就挂了？

### ISSUE THREAD

**Issue by vuchan** [xiaoming2028/FreeNet#20]
1. 从本机 ping 服务器 IP 依然能 ping 通
2. 试过了 reboot, reinstall, restart 等各种
3. 试过了 更换端口。。。
4. 试过了完全另一个脚本 ./shadowsocksR 等

但是还是没用，所以我必须使用 hostwinds 的切换 IP 吗？但是 IP 能 ping 通的。

**Comment by xiaoming2028** [comment]
换个IP试试吧
